name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=9-s=%xi$8!a#8=*6poe3cf*wxb8quc83f81tv(6^&2h@@=6wuo
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=P3CTPsElNXXwHJTKp17I8Fpe
      - PASSAGE_API_KEY=kiTuhSM1ao.WFwUyiiyTHoKrSgqY4y8SmopiXvaG75JzLHcwlRnw2fwaDsAsRQGaqreXqTLEZ3d
    ports:
      - 8000:8000
